trigger:  
  branches:
    include:
      - none

variables:
- group: tfstate_infos

- group: azure_service_connection

- name: terraformWorkingDirectory
  value: 'Devops/Infrastructure'

stages:
  - stage: TerraformPrepare
    displayName: 'Terraform — Init e validate'
    jobs:
      - job: Prepare
        displayName: 'Prepare'
        pool:
          vmImage: ubuntu-latest
        steps:
          - checkout: self
            displayName: 'Checkout'

          - task: TerraformInstaller@1
            displayName: 'Instalar Terraform'
            inputs:
              terraformVersion: 'latest'

          - task: TerraformTask@5
            displayName: 'Terraform init'
            inputs:
              provider: 'azurerm'
              command: 'init'
              workingDirectory: '$(terraformWorkingDirectory)'
              backendServiceArm: '$(azureServiceConnection)'
              backendAzureRmResourceGroupName: '$(backendAzureRmResourceGroupName)'
              backendAzureRmStorageAccountName: '$(backendAzureRmStorageAccountName)'
              backendAzureRmContainerName: '$(backendAzureRmContainerName)'
              backendAzureRmKey: '$(backendAzureRmKey)'

          - task: TerraformTask@5
            displayName: 'Terraform validate'
            inputs:
              provider: 'azurerm'
              command: 'validate'
              workingDirectory: '$(terraformWorkingDirectory)'
              environmentServiceNameAzureRM: '$(azureServiceConnection)'

          - task: TerraformTask@5
            displayName: 'Terraform plan'
            inputs:
              provider: 'azurerm'
              command: 'plan'
              workingDirectory: '$(terraformWorkingDirectory)'
              commandOptions: '-var-file=dev.tfvars -input=false -detailed-exitcode -out=tfplan'
              environmentServiceNameAzureRM: '$(azureServiceConnection)'
